// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pix_average (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        StreamIn_V_Data_V_dout,
        StreamIn_V_Data_V_empty_n,
        StreamIn_V_Data_V_read,
        StreamIn_V_User_V_dout,
        StreamIn_V_User_V_empty_n,
        StreamIn_V_User_V_read,
        StreamOut_V_Data_V_din,
        StreamOut_V_Data_V_full_n,
        StreamOut_V_Data_V_write,
        StreamOut_V_User_V_din,
        StreamOut_V_User_V_full_n,
        StreamOut_V_User_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_state13 = 4'd4;
parameter    ap_ST_fsm_state14 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] StreamIn_V_Data_V_dout;
input   StreamIn_V_Data_V_empty_n;
output   StreamIn_V_Data_V_read;
input  [3:0] StreamIn_V_User_V_dout;
input   StreamIn_V_User_V_empty_n;
output   StreamIn_V_User_V_read;
output  [127:0] StreamOut_V_Data_V_din;
input   StreamOut_V_Data_V_full_n;
output   StreamOut_V_Data_V_write;
output  [3:0] StreamOut_V_User_V_din;
input   StreamOut_V_User_V_full_n;
output   StreamOut_V_User_V_write;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [31:0] cntr;
reg   [13:0] sum_V_0_address0;
reg    sum_V_0_ce0;
wire   [20:0] sum_V_0_q0;
reg   [13:0] sum_V_0_address1;
reg    sum_V_0_ce1;
reg    sum_V_0_we1;
reg   [20:0] sum_V_0_d1;
reg   [13:0] sum_V_1_address0;
reg    sum_V_1_ce0;
wire   [20:0] sum_V_1_q0;
reg   [13:0] sum_V_1_address1;
reg    sum_V_1_ce1;
reg    sum_V_1_we1;
reg   [20:0] sum_V_1_d1;
reg   [13:0] sum_V_2_address0;
reg    sum_V_2_ce0;
wire   [20:0] sum_V_2_q0;
reg   [13:0] sum_V_2_address1;
reg    sum_V_2_ce1;
reg    sum_V_2_we1;
reg   [20:0] sum_V_2_d1;
reg   [13:0] sum_V_3_address0;
reg    sum_V_3_ce0;
wire   [20:0] sum_V_3_q0;
reg   [13:0] sum_V_3_address1;
reg    sum_V_3_ce1;
reg    sum_V_3_we1;
reg   [20:0] sum_V_3_d1;
reg   [13:0] sum_V_4_address0;
reg    sum_V_4_ce0;
wire   [20:0] sum_V_4_q0;
reg   [13:0] sum_V_4_address1;
reg    sum_V_4_ce1;
reg    sum_V_4_we1;
reg   [20:0] sum_V_4_d1;
reg   [13:0] sum_V_5_address0;
reg    sum_V_5_ce0;
wire   [20:0] sum_V_5_q0;
reg   [13:0] sum_V_5_address1;
reg    sum_V_5_ce1;
reg    sum_V_5_we1;
reg   [20:0] sum_V_5_d1;
reg   [13:0] sum_V_6_address0;
reg    sum_V_6_ce0;
wire   [20:0] sum_V_6_q0;
reg   [13:0] sum_V_6_address1;
reg    sum_V_6_ce1;
reg    sum_V_6_we1;
reg   [20:0] sum_V_6_d1;
reg   [13:0] sum_V_7_address0;
reg    sum_V_7_ce0;
wire   [20:0] sum_V_7_q0;
reg   [13:0] sum_V_7_address1;
reg    sum_V_7_ce1;
reg    sum_V_7_we1;
reg   [20:0] sum_V_7_d1;
reg    StreamIn_V_Data_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg    StreamIn_V_User_V_blk_n;
reg    StreamOut_V_Data_V_blk_n;
reg    ap_enable_reg_pp0_iter10;
reg   [0:0] tmp_s_reg_860;
reg   [0:0] tmp_s_reg_860_pp0_iter9_reg;
reg    StreamOut_V_User_V_blk_n;
reg   [13:0] i_reg_388;
reg   [20:0] reg_399;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    StreamIn_V_Data_V0_status;
reg    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    StreamOut_V_Data_V1_status;
reg    ap_block_state12_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_6_reg_851;
reg   [0:0] tmp_8_reg_855;
reg   [20:0] reg_403;
reg   [20:0] reg_407;
reg   [20:0] reg_411;
reg   [20:0] reg_415;
reg   [20:0] reg_419;
reg   [20:0] reg_423;
reg   [20:0] reg_427;
reg   [31:0] cntr_load_reg_846;
reg    ap_block_state1;
wire   [0:0] tmp_6_fu_435_p2;
wire   [0:0] tmp_8_fu_441_p2;
wire   [0:0] tmp_s_fu_447_p2;
wire    ap_CS_fsm_pp0_stage0;
reg   [0:0] tmp_s_reg_860_pp0_iter1_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter2_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter3_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter4_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter5_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter6_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter7_reg;
reg   [0:0] tmp_s_reg_860_pp0_iter8_reg;
wire   [13:0] i_2_fu_453_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [13:0] sum_V_0_addr_1_reg_869;
reg   [13:0] sum_V_0_addr_1_reg_869_pp0_iter1_reg;
reg   [13:0] sum_V_0_addr_1_reg_869_pp0_iter2_reg;
reg   [13:0] sum_V_0_addr_1_reg_869_pp0_iter3_reg;
reg   [13:0] sum_V_1_addr_1_reg_875;
reg   [13:0] sum_V_1_addr_1_reg_875_pp0_iter1_reg;
reg   [13:0] sum_V_1_addr_1_reg_875_pp0_iter2_reg;
reg   [13:0] sum_V_1_addr_1_reg_875_pp0_iter3_reg;
reg   [13:0] sum_V_2_addr_1_reg_881;
reg   [13:0] sum_V_2_addr_1_reg_881_pp0_iter1_reg;
reg   [13:0] sum_V_2_addr_1_reg_881_pp0_iter2_reg;
reg   [13:0] sum_V_2_addr_1_reg_881_pp0_iter3_reg;
reg   [13:0] sum_V_3_addr_1_reg_887;
reg   [13:0] sum_V_3_addr_1_reg_887_pp0_iter1_reg;
reg   [13:0] sum_V_3_addr_1_reg_887_pp0_iter2_reg;
reg   [13:0] sum_V_3_addr_1_reg_887_pp0_iter3_reg;
reg   [13:0] sum_V_4_addr_1_reg_893;
reg   [13:0] sum_V_4_addr_1_reg_893_pp0_iter1_reg;
reg   [13:0] sum_V_4_addr_1_reg_893_pp0_iter2_reg;
reg   [13:0] sum_V_4_addr_1_reg_893_pp0_iter3_reg;
reg   [13:0] sum_V_5_addr_1_reg_899;
reg   [13:0] sum_V_5_addr_1_reg_899_pp0_iter1_reg;
reg   [13:0] sum_V_5_addr_1_reg_899_pp0_iter2_reg;
reg   [13:0] sum_V_5_addr_1_reg_899_pp0_iter3_reg;
reg   [13:0] sum_V_6_addr_1_reg_905;
reg   [13:0] sum_V_6_addr_1_reg_905_pp0_iter1_reg;
reg   [13:0] sum_V_6_addr_1_reg_905_pp0_iter2_reg;
reg   [13:0] sum_V_6_addr_1_reg_905_pp0_iter3_reg;
reg   [13:0] sum_V_7_addr_1_reg_911;
reg   [13:0] sum_V_7_addr_1_reg_911_pp0_iter1_reg;
reg   [13:0] sum_V_7_addr_1_reg_911_pp0_iter2_reg;
reg   [13:0] sum_V_7_addr_1_reg_911_pp0_iter3_reg;
reg   [13:0] sum_V_0_addr_reg_917;
reg   [13:0] sum_V_0_addr_reg_917_pp0_iter1_reg;
reg   [13:0] sum_V_0_addr_reg_917_pp0_iter2_reg;
reg   [13:0] sum_V_0_addr_reg_917_pp0_iter3_reg;
reg   [13:0] sum_V_1_addr_reg_923;
reg   [13:0] sum_V_1_addr_reg_923_pp0_iter1_reg;
reg   [13:0] sum_V_1_addr_reg_923_pp0_iter2_reg;
reg   [13:0] sum_V_1_addr_reg_923_pp0_iter3_reg;
reg   [13:0] sum_V_2_addr_reg_929;
reg   [13:0] sum_V_2_addr_reg_929_pp0_iter1_reg;
reg   [13:0] sum_V_2_addr_reg_929_pp0_iter2_reg;
reg   [13:0] sum_V_2_addr_reg_929_pp0_iter3_reg;
reg   [13:0] sum_V_3_addr_reg_935;
reg   [13:0] sum_V_3_addr_reg_935_pp0_iter1_reg;
reg   [13:0] sum_V_3_addr_reg_935_pp0_iter2_reg;
reg   [13:0] sum_V_3_addr_reg_935_pp0_iter3_reg;
reg   [13:0] sum_V_4_addr_reg_941;
reg   [13:0] sum_V_4_addr_reg_941_pp0_iter1_reg;
reg   [13:0] sum_V_4_addr_reg_941_pp0_iter2_reg;
reg   [13:0] sum_V_4_addr_reg_941_pp0_iter3_reg;
reg   [13:0] sum_V_5_addr_reg_947;
reg   [13:0] sum_V_5_addr_reg_947_pp0_iter1_reg;
reg   [13:0] sum_V_5_addr_reg_947_pp0_iter2_reg;
reg   [13:0] sum_V_5_addr_reg_947_pp0_iter3_reg;
reg   [13:0] sum_V_6_addr_reg_953;
reg   [13:0] sum_V_6_addr_reg_953_pp0_iter1_reg;
reg   [13:0] sum_V_6_addr_reg_953_pp0_iter2_reg;
reg   [13:0] sum_V_6_addr_reg_953_pp0_iter3_reg;
reg   [13:0] sum_V_7_addr_reg_959;
reg   [13:0] sum_V_7_addr_reg_959_pp0_iter1_reg;
reg   [13:0] sum_V_7_addr_reg_959_pp0_iter2_reg;
reg   [13:0] sum_V_7_addr_reg_959_pp0_iter3_reg;
reg   [127:0] tmp_Data_V_5_reg_965;
reg   [127:0] tmp_Data_V_5_reg_965_pp0_iter3_reg;
reg   [127:0] tmp_Data_V_5_reg_965_pp0_iter4_reg;
reg   [127:0] tmp_Data_V_5_reg_965_pp0_iter5_reg;
reg   [127:0] tmp_Data_V_5_reg_965_pp0_iter6_reg;
reg   [127:0] tmp_Data_V_5_reg_965_pp0_iter7_reg;
reg   [127:0] tmp_Data_V_5_reg_965_pp0_iter8_reg;
reg   [3:0] tmp_User_V_reg_978;
reg   [3:0] tmp_User_V_reg_978_pp0_iter3_reg;
reg   [3:0] tmp_User_V_reg_978_pp0_iter4_reg;
reg   [3:0] tmp_User_V_reg_978_pp0_iter5_reg;
reg   [3:0] tmp_User_V_reg_978_pp0_iter6_reg;
reg   [3:0] tmp_User_V_reg_978_pp0_iter7_reg;
reg   [3:0] tmp_User_V_reg_978_pp0_iter8_reg;
reg   [3:0] tmp_User_V_reg_978_pp0_iter9_reg;
wire   [20:0] ret_V_7_fu_578_p2;
reg   [20:0] ret_V_7_reg_1023;
wire   [20:0] ret_V_7_1_fu_597_p2;
reg   [20:0] ret_V_7_1_reg_1028;
wire   [20:0] ret_V_7_2_fu_616_p2;
reg   [20:0] ret_V_7_2_reg_1033;
wire   [20:0] ret_V_7_3_fu_635_p2;
reg   [20:0] ret_V_7_3_reg_1038;
wire   [20:0] ret_V_7_4_fu_654_p2;
reg   [20:0] ret_V_7_4_reg_1043;
wire   [20:0] ret_V_7_5_fu_673_p2;
reg   [20:0] ret_V_7_5_reg_1048;
wire   [20:0] ret_V_7_6_fu_692_p2;
reg   [20:0] ret_V_7_6_reg_1053;
wire   [20:0] ret_V_7_7_fu_711_p2;
reg   [20:0] ret_V_7_7_reg_1058;
reg   [15:0] tmp_V_0_trunc_reg_1063;
reg   [15:0] tmp_V_1_trunc_reg_1068;
reg   [15:0] tmp_V_2_trunc_reg_1073;
reg   [15:0] tmp_V_3_trunc_reg_1078;
reg   [15:0] tmp_V_4_trunc_reg_1083;
reg   [15:0] tmp_V_5_trunc_reg_1088;
reg   [15:0] tmp_V_6_trunc_reg_1093;
reg   [15:0] tmp_V_7_trunc_reg_1098;
wire   [31:0] tmp_5_fu_822_p2;
reg   [31:0] tmp_5_reg_1103;
wire    ap_CS_fsm_state13;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
wire   [63:0] i3_fu_459_p1;
wire   [63:0] i2_fu_471_p1;
reg    StreamIn_V_Data_V0_update;
reg    StreamOut_V_Data_V1_update;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] storemerge_fu_827_p3;
wire    ap_CS_fsm_state14;
reg   [127:0] tmp_Data_V_fu_158;
wire   [127:0] p_Result_12_7_fu_797_p9;
wire   [20:0] grp_fu_495_p0;
wire   [22:0] grp_fu_495_p1;
wire   [20:0] grp_fu_505_p0;
wire   [22:0] grp_fu_505_p1;
wire   [20:0] grp_fu_515_p0;
wire   [22:0] grp_fu_515_p1;
wire   [20:0] grp_fu_525_p0;
wire   [22:0] grp_fu_525_p1;
wire   [20:0] grp_fu_535_p0;
wire   [22:0] grp_fu_535_p1;
wire   [20:0] grp_fu_545_p0;
wire   [22:0] grp_fu_545_p1;
wire   [20:0] grp_fu_555_p0;
wire   [22:0] grp_fu_555_p1;
wire   [20:0] grp_fu_565_p0;
wire   [22:0] grp_fu_565_p1;
wire   [15:0] tmp_9_fu_571_p1;
wire   [20:0] rhs_V_fu_574_p1;
wire   [15:0] p_Result_1_fu_584_p4;
wire   [20:0] rhs_V_1_fu_593_p1;
wire   [15:0] p_Result_2_fu_603_p4;
wire   [20:0] rhs_V_2_fu_612_p1;
wire   [15:0] p_Result_3_fu_622_p4;
wire   [20:0] rhs_V_3_fu_631_p1;
wire   [15:0] p_Result_4_fu_641_p4;
wire   [20:0] rhs_V_4_fu_650_p1;
wire   [15:0] p_Result_5_fu_660_p4;
wire   [20:0] rhs_V_5_fu_669_p1;
wire   [15:0] p_Result_6_fu_679_p4;
wire   [20:0] rhs_V_6_fu_688_p1;
wire   [15:0] p_Result_7_fu_698_p4;
wire   [20:0] rhs_V_7_fu_707_p1;
wire   [43:0] grp_fu_495_p2;
wire   [43:0] grp_fu_505_p2;
wire   [43:0] grp_fu_515_p2;
wire   [43:0] grp_fu_525_p2;
wire   [43:0] grp_fu_535_p2;
wire   [43:0] grp_fu_545_p2;
wire   [43:0] grp_fu_555_p2;
wire   [43:0] grp_fu_565_p2;
reg    grp_fu_495_ce;
reg    grp_fu_505_ce;
reg    grp_fu_515_ce;
reg    grp_fu_525_ce;
reg    grp_fu_535_ce;
reg    grp_fu_545_ce;
reg    grp_fu_555_ce;
reg    grp_fu_565_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [43:0] grp_fu_495_p00;
wire   [43:0] grp_fu_505_p00;
wire   [43:0] grp_fu_515_p00;
wire   [43:0] grp_fu_525_p00;
wire   [43:0] grp_fu_535_p00;
wire   [43:0] grp_fu_545_p00;
wire   [43:0] grp_fu_555_p00;
wire   [43:0] grp_fu_565_p00;
reg    ap_condition_976;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 cntr = 32'd0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
end

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_0_address0),
    .ce0(sum_V_0_ce0),
    .q0(sum_V_0_q0),
    .address1(sum_V_0_address1),
    .ce1(sum_V_0_ce1),
    .we1(sum_V_0_we1),
    .d1(sum_V_0_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_1_address0),
    .ce0(sum_V_1_ce0),
    .q0(sum_V_1_q0),
    .address1(sum_V_1_address1),
    .ce1(sum_V_1_ce1),
    .we1(sum_V_1_we1),
    .d1(sum_V_1_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_2_address0),
    .ce0(sum_V_2_ce0),
    .q0(sum_V_2_q0),
    .address1(sum_V_2_address1),
    .ce1(sum_V_2_ce1),
    .we1(sum_V_2_we1),
    .d1(sum_V_2_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_3_address0),
    .ce0(sum_V_3_ce0),
    .q0(sum_V_3_q0),
    .address1(sum_V_3_address1),
    .ce1(sum_V_3_ce1),
    .we1(sum_V_3_we1),
    .d1(sum_V_3_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_4_address0),
    .ce0(sum_V_4_ce0),
    .q0(sum_V_4_q0),
    .address1(sum_V_4_address1),
    .ce1(sum_V_4_ce1),
    .we1(sum_V_4_we1),
    .d1(sum_V_4_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_5_address0),
    .ce0(sum_V_5_ce0),
    .q0(sum_V_5_q0),
    .address1(sum_V_5_address1),
    .ce1(sum_V_5_ce1),
    .we1(sum_V_5_we1),
    .d1(sum_V_5_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_6_address0),
    .ce0(sum_V_6_ce0),
    .q0(sum_V_6_q0),
    .address1(sum_V_6_address1),
    .ce1(sum_V_6_ce1),
    .we1(sum_V_6_we1),
    .d1(sum_V_6_d1)
);

pix_average_sum_V_0 #(
    .DataWidth( 21 ),
    .AddressRange( 10240 ),
    .AddressWidth( 14 ))
sum_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sum_V_7_address0),
    .ce0(sum_V_7_ce0),
    .q0(sum_V_7_q0),
    .address1(sum_V_7_address1),
    .ce1(sum_V_7_ce1),
    .we1(sum_V_7_we1),
    .d1(sum_V_7_d1)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_495_p0),
    .din1(grp_fu_495_p1),
    .ce(grp_fu_495_ce),
    .dout(grp_fu_495_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_505_p0),
    .din1(grp_fu_505_p1),
    .ce(grp_fu_505_ce),
    .dout(grp_fu_505_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_515_p0),
    .din1(grp_fu_515_p1),
    .ce(grp_fu_515_ce),
    .dout(grp_fu_515_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_525_p0),
    .din1(grp_fu_525_p1),
    .ce(grp_fu_525_ce),
    .dout(grp_fu_525_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_535_p0),
    .din1(grp_fu_535_p1),
    .ce(grp_fu_535_ce),
    .dout(grp_fu_535_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_545_p0),
    .din1(grp_fu_545_p1),
    .ce(grp_fu_545_ce),
    .dout(grp_fu_545_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_555_p0),
    .din1(grp_fu_555_p1),
    .ce(grp_fu_555_ce),
    .dout(grp_fu_555_p2)
);

myproject_axi_mul_21ns_23ns_44_6_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 44 ))
myproject_axi_mul_21ns_23ns_44_6_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_565_p0),
    .din1(grp_fu_565_p1),
    .ce(grp_fu_565_ce),
    .dout(grp_fu_565_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0))) begin
        i_reg_388 <= i_2_fu_453_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_388 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            tmp_Data_V_fu_158 <= tmp_Data_V_5_reg_965_pp0_iter8_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            tmp_Data_V_fu_158 <= p_Result_12_7_fu_797_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        cntr <= storemerge_fu_827_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cntr_load_reg_846 <= cntr;
        tmp_6_reg_851 <= tmp_6_fu_435_p2;
        tmp_8_reg_855 <= tmp_8_fu_441_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        reg_399 <= sum_V_0_q0;
        reg_403 <= sum_V_1_q0;
        reg_407 <= sum_V_2_q0;
        reg_411 <= sum_V_3_q0;
        reg_415 <= sum_V_4_q0;
        reg_419 <= sum_V_5_q0;
        reg_423 <= sum_V_6_q0;
        reg_427 <= sum_V_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ret_V_7_1_reg_1028 <= ret_V_7_1_fu_597_p2;
        ret_V_7_2_reg_1033 <= ret_V_7_2_fu_616_p2;
        ret_V_7_3_reg_1038 <= ret_V_7_3_fu_635_p2;
        ret_V_7_4_reg_1043 <= ret_V_7_4_fu_654_p2;
        ret_V_7_5_reg_1048 <= ret_V_7_5_fu_673_p2;
        ret_V_7_6_reg_1053 <= ret_V_7_6_fu_692_p2;
        ret_V_7_7_reg_1058 <= ret_V_7_7_fu_711_p2;
        ret_V_7_reg_1023 <= ret_V_7_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0))) begin
        sum_V_0_addr_1_reg_869 <= i3_fu_459_p1;
        sum_V_1_addr_1_reg_875 <= i3_fu_459_p1;
        sum_V_2_addr_1_reg_881 <= i3_fu_459_p1;
        sum_V_3_addr_1_reg_887 <= i3_fu_459_p1;
        sum_V_4_addr_1_reg_893 <= i3_fu_459_p1;
        sum_V_5_addr_1_reg_899 <= i3_fu_459_p1;
        sum_V_6_addr_1_reg_905 <= i3_fu_459_p1;
        sum_V_7_addr_1_reg_911 <= i3_fu_459_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_0_addr_1_reg_869_pp0_iter1_reg <= sum_V_0_addr_1_reg_869;
        sum_V_0_addr_reg_917_pp0_iter1_reg <= sum_V_0_addr_reg_917;
        sum_V_1_addr_1_reg_875_pp0_iter1_reg <= sum_V_1_addr_1_reg_875;
        sum_V_1_addr_reg_923_pp0_iter1_reg <= sum_V_1_addr_reg_923;
        sum_V_2_addr_1_reg_881_pp0_iter1_reg <= sum_V_2_addr_1_reg_881;
        sum_V_2_addr_reg_929_pp0_iter1_reg <= sum_V_2_addr_reg_929;
        sum_V_3_addr_1_reg_887_pp0_iter1_reg <= sum_V_3_addr_1_reg_887;
        sum_V_3_addr_reg_935_pp0_iter1_reg <= sum_V_3_addr_reg_935;
        sum_V_4_addr_1_reg_893_pp0_iter1_reg <= sum_V_4_addr_1_reg_893;
        sum_V_4_addr_reg_941_pp0_iter1_reg <= sum_V_4_addr_reg_941;
        sum_V_5_addr_1_reg_899_pp0_iter1_reg <= sum_V_5_addr_1_reg_899;
        sum_V_5_addr_reg_947_pp0_iter1_reg <= sum_V_5_addr_reg_947;
        sum_V_6_addr_1_reg_905_pp0_iter1_reg <= sum_V_6_addr_1_reg_905;
        sum_V_6_addr_reg_953_pp0_iter1_reg <= sum_V_6_addr_reg_953;
        sum_V_7_addr_1_reg_911_pp0_iter1_reg <= sum_V_7_addr_1_reg_911;
        sum_V_7_addr_reg_959_pp0_iter1_reg <= sum_V_7_addr_reg_959;
        tmp_s_reg_860 <= tmp_s_fu_447_p2;
        tmp_s_reg_860_pp0_iter1_reg <= tmp_s_reg_860;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        sum_V_0_addr_1_reg_869_pp0_iter2_reg <= sum_V_0_addr_1_reg_869_pp0_iter1_reg;
        sum_V_0_addr_1_reg_869_pp0_iter3_reg <= sum_V_0_addr_1_reg_869_pp0_iter2_reg;
        sum_V_0_addr_reg_917_pp0_iter2_reg <= sum_V_0_addr_reg_917_pp0_iter1_reg;
        sum_V_0_addr_reg_917_pp0_iter3_reg <= sum_V_0_addr_reg_917_pp0_iter2_reg;
        sum_V_1_addr_1_reg_875_pp0_iter2_reg <= sum_V_1_addr_1_reg_875_pp0_iter1_reg;
        sum_V_1_addr_1_reg_875_pp0_iter3_reg <= sum_V_1_addr_1_reg_875_pp0_iter2_reg;
        sum_V_1_addr_reg_923_pp0_iter2_reg <= sum_V_1_addr_reg_923_pp0_iter1_reg;
        sum_V_1_addr_reg_923_pp0_iter3_reg <= sum_V_1_addr_reg_923_pp0_iter2_reg;
        sum_V_2_addr_1_reg_881_pp0_iter2_reg <= sum_V_2_addr_1_reg_881_pp0_iter1_reg;
        sum_V_2_addr_1_reg_881_pp0_iter3_reg <= sum_V_2_addr_1_reg_881_pp0_iter2_reg;
        sum_V_2_addr_reg_929_pp0_iter2_reg <= sum_V_2_addr_reg_929_pp0_iter1_reg;
        sum_V_2_addr_reg_929_pp0_iter3_reg <= sum_V_2_addr_reg_929_pp0_iter2_reg;
        sum_V_3_addr_1_reg_887_pp0_iter2_reg <= sum_V_3_addr_1_reg_887_pp0_iter1_reg;
        sum_V_3_addr_1_reg_887_pp0_iter3_reg <= sum_V_3_addr_1_reg_887_pp0_iter2_reg;
        sum_V_3_addr_reg_935_pp0_iter2_reg <= sum_V_3_addr_reg_935_pp0_iter1_reg;
        sum_V_3_addr_reg_935_pp0_iter3_reg <= sum_V_3_addr_reg_935_pp0_iter2_reg;
        sum_V_4_addr_1_reg_893_pp0_iter2_reg <= sum_V_4_addr_1_reg_893_pp0_iter1_reg;
        sum_V_4_addr_1_reg_893_pp0_iter3_reg <= sum_V_4_addr_1_reg_893_pp0_iter2_reg;
        sum_V_4_addr_reg_941_pp0_iter2_reg <= sum_V_4_addr_reg_941_pp0_iter1_reg;
        sum_V_4_addr_reg_941_pp0_iter3_reg <= sum_V_4_addr_reg_941_pp0_iter2_reg;
        sum_V_5_addr_1_reg_899_pp0_iter2_reg <= sum_V_5_addr_1_reg_899_pp0_iter1_reg;
        sum_V_5_addr_1_reg_899_pp0_iter3_reg <= sum_V_5_addr_1_reg_899_pp0_iter2_reg;
        sum_V_5_addr_reg_947_pp0_iter2_reg <= sum_V_5_addr_reg_947_pp0_iter1_reg;
        sum_V_5_addr_reg_947_pp0_iter3_reg <= sum_V_5_addr_reg_947_pp0_iter2_reg;
        sum_V_6_addr_1_reg_905_pp0_iter2_reg <= sum_V_6_addr_1_reg_905_pp0_iter1_reg;
        sum_V_6_addr_1_reg_905_pp0_iter3_reg <= sum_V_6_addr_1_reg_905_pp0_iter2_reg;
        sum_V_6_addr_reg_953_pp0_iter2_reg <= sum_V_6_addr_reg_953_pp0_iter1_reg;
        sum_V_6_addr_reg_953_pp0_iter3_reg <= sum_V_6_addr_reg_953_pp0_iter2_reg;
        sum_V_7_addr_1_reg_911_pp0_iter2_reg <= sum_V_7_addr_1_reg_911_pp0_iter1_reg;
        sum_V_7_addr_1_reg_911_pp0_iter3_reg <= sum_V_7_addr_1_reg_911_pp0_iter2_reg;
        sum_V_7_addr_reg_959_pp0_iter2_reg <= sum_V_7_addr_reg_959_pp0_iter1_reg;
        sum_V_7_addr_reg_959_pp0_iter3_reg <= sum_V_7_addr_reg_959_pp0_iter2_reg;
        tmp_Data_V_5_reg_965 <= StreamIn_V_Data_V_dout;
        tmp_Data_V_5_reg_965_pp0_iter3_reg <= tmp_Data_V_5_reg_965;
        tmp_Data_V_5_reg_965_pp0_iter4_reg <= tmp_Data_V_5_reg_965_pp0_iter3_reg;
        tmp_Data_V_5_reg_965_pp0_iter5_reg <= tmp_Data_V_5_reg_965_pp0_iter4_reg;
        tmp_Data_V_5_reg_965_pp0_iter6_reg <= tmp_Data_V_5_reg_965_pp0_iter5_reg;
        tmp_Data_V_5_reg_965_pp0_iter7_reg <= tmp_Data_V_5_reg_965_pp0_iter6_reg;
        tmp_Data_V_5_reg_965_pp0_iter8_reg <= tmp_Data_V_5_reg_965_pp0_iter7_reg;
        tmp_User_V_reg_978 <= StreamIn_V_User_V_dout;
        tmp_User_V_reg_978_pp0_iter3_reg <= tmp_User_V_reg_978;
        tmp_User_V_reg_978_pp0_iter4_reg <= tmp_User_V_reg_978_pp0_iter3_reg;
        tmp_User_V_reg_978_pp0_iter5_reg <= tmp_User_V_reg_978_pp0_iter4_reg;
        tmp_User_V_reg_978_pp0_iter6_reg <= tmp_User_V_reg_978_pp0_iter5_reg;
        tmp_User_V_reg_978_pp0_iter7_reg <= tmp_User_V_reg_978_pp0_iter6_reg;
        tmp_User_V_reg_978_pp0_iter8_reg <= tmp_User_V_reg_978_pp0_iter7_reg;
        tmp_User_V_reg_978_pp0_iter9_reg <= tmp_User_V_reg_978_pp0_iter8_reg;
        tmp_s_reg_860_pp0_iter2_reg <= tmp_s_reg_860_pp0_iter1_reg;
        tmp_s_reg_860_pp0_iter3_reg <= tmp_s_reg_860_pp0_iter2_reg;
        tmp_s_reg_860_pp0_iter4_reg <= tmp_s_reg_860_pp0_iter3_reg;
        tmp_s_reg_860_pp0_iter5_reg <= tmp_s_reg_860_pp0_iter4_reg;
        tmp_s_reg_860_pp0_iter6_reg <= tmp_s_reg_860_pp0_iter5_reg;
        tmp_s_reg_860_pp0_iter7_reg <= tmp_s_reg_860_pp0_iter6_reg;
        tmp_s_reg_860_pp0_iter8_reg <= tmp_s_reg_860_pp0_iter7_reg;
        tmp_s_reg_860_pp0_iter9_reg <= tmp_s_reg_860_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0))) begin
        sum_V_0_addr_reg_917 <= i2_fu_471_p1;
        sum_V_1_addr_reg_923 <= i2_fu_471_p1;
        sum_V_2_addr_reg_929 <= i2_fu_471_p1;
        sum_V_3_addr_reg_935 <= i2_fu_471_p1;
        sum_V_4_addr_reg_941 <= i2_fu_471_p1;
        sum_V_5_addr_reg_947 <= i2_fu_471_p1;
        sum_V_6_addr_reg_953 <= i2_fu_471_p1;
        sum_V_7_addr_reg_959 <= i2_fu_471_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_8_reg_855 == 1'd0))) begin
        tmp_5_reg_1103 <= tmp_5_fu_822_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0))) begin
        tmp_V_0_trunc_reg_1063 <= {{grp_fu_495_p2[40:25]}};
        tmp_V_1_trunc_reg_1068 <= {{grp_fu_505_p2[40:25]}};
        tmp_V_2_trunc_reg_1073 <= {{grp_fu_515_p2[40:25]}};
        tmp_V_3_trunc_reg_1078 <= {{grp_fu_525_p2[40:25]}};
        tmp_V_4_trunc_reg_1083 <= {{grp_fu_535_p2[40:25]}};
        tmp_V_5_trunc_reg_1088 <= {{grp_fu_545_p2[40:25]}};
        tmp_V_6_trunc_reg_1093 <= {{grp_fu_555_p2[40:25]}};
        tmp_V_7_trunc_reg_1098 <= {{grp_fu_565_p2[40:25]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        StreamIn_V_Data_V0_update = 1'b1;
    end else begin
        StreamIn_V_Data_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        StreamIn_V_Data_V_blk_n = StreamIn_V_Data_V_empty_n;
    end else begin
        StreamIn_V_Data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        StreamIn_V_User_V_blk_n = StreamIn_V_User_V_empty_n;
    end else begin
        StreamIn_V_User_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0))) begin
        StreamOut_V_Data_V1_update = 1'b1;
    end else begin
        StreamOut_V_Data_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        StreamOut_V_Data_V_blk_n = StreamOut_V_Data_V_full_n;
    end else begin
        StreamOut_V_Data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        StreamOut_V_User_V_blk_n = StreamOut_V_User_V_full_n;
    end else begin
        StreamOut_V_User_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((tmp_s_fu_447_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_495_ce = 1'b1;
    end else begin
        grp_fu_495_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_505_ce = 1'b1;
    end else begin
        grp_fu_505_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_515_ce = 1'b1;
    end else begin
        grp_fu_515_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_525_ce = 1'b1;
    end else begin
        grp_fu_525_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_535_ce = 1'b1;
    end else begin
        grp_fu_535_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_545_ce = 1'b1;
    end else begin
        grp_fu_545_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_555_ce = 1'b1;
    end else begin
        grp_fu_555_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_565_ce = 1'b1;
    end else begin
        grp_fu_565_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_0_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_0_address0 = i3_fu_459_p1;
        end else begin
            sum_V_0_address0 = 'bx;
        end
    end else begin
        sum_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_0_address1 = sum_V_0_addr_reg_917_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_0_address1 = sum_V_0_addr_1_reg_869_pp0_iter3_reg;
        end else begin
            sum_V_0_address1 = 'bx;
        end
    end else begin
        sum_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_0_ce0 = 1'b1;
    end else begin
        sum_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_0_ce1 = 1'b1;
    end else begin
        sum_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_0_d1 = ret_V_7_reg_1023;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_0_d1 = 21'd0;
        end else begin
            sum_V_0_d1 = 'bx;
        end
    end else begin
        sum_V_0_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_0_we1 = 1'b1;
    end else begin
        sum_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_1_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_1_address0 = i3_fu_459_p1;
        end else begin
            sum_V_1_address0 = 'bx;
        end
    end else begin
        sum_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_1_address1 = sum_V_1_addr_reg_923_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_1_address1 = sum_V_1_addr_1_reg_875_pp0_iter3_reg;
        end else begin
            sum_V_1_address1 = 'bx;
        end
    end else begin
        sum_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_1_ce0 = 1'b1;
    end else begin
        sum_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_1_ce1 = 1'b1;
    end else begin
        sum_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_1_d1 = ret_V_7_1_reg_1028;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_1_d1 = 21'd0;
        end else begin
            sum_V_1_d1 = 'bx;
        end
    end else begin
        sum_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_1_we1 = 1'b1;
    end else begin
        sum_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_2_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_2_address0 = i3_fu_459_p1;
        end else begin
            sum_V_2_address0 = 'bx;
        end
    end else begin
        sum_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_2_address1 = sum_V_2_addr_reg_929_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_2_address1 = sum_V_2_addr_1_reg_881_pp0_iter3_reg;
        end else begin
            sum_V_2_address1 = 'bx;
        end
    end else begin
        sum_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_2_ce0 = 1'b1;
    end else begin
        sum_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_2_ce1 = 1'b1;
    end else begin
        sum_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_2_d1 = ret_V_7_2_reg_1033;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_2_d1 = 21'd0;
        end else begin
            sum_V_2_d1 = 'bx;
        end
    end else begin
        sum_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_2_we1 = 1'b1;
    end else begin
        sum_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_3_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_3_address0 = i3_fu_459_p1;
        end else begin
            sum_V_3_address0 = 'bx;
        end
    end else begin
        sum_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_3_address1 = sum_V_3_addr_reg_935_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_3_address1 = sum_V_3_addr_1_reg_887_pp0_iter3_reg;
        end else begin
            sum_V_3_address1 = 'bx;
        end
    end else begin
        sum_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_3_ce0 = 1'b1;
    end else begin
        sum_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_3_ce1 = 1'b1;
    end else begin
        sum_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_3_d1 = ret_V_7_3_reg_1038;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_3_d1 = 21'd0;
        end else begin
            sum_V_3_d1 = 'bx;
        end
    end else begin
        sum_V_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_3_we1 = 1'b1;
    end else begin
        sum_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_4_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_4_address0 = i3_fu_459_p1;
        end else begin
            sum_V_4_address0 = 'bx;
        end
    end else begin
        sum_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_4_address1 = sum_V_4_addr_reg_941_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_4_address1 = sum_V_4_addr_1_reg_893_pp0_iter3_reg;
        end else begin
            sum_V_4_address1 = 'bx;
        end
    end else begin
        sum_V_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_4_ce0 = 1'b1;
    end else begin
        sum_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_4_ce1 = 1'b1;
    end else begin
        sum_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_4_d1 = ret_V_7_4_reg_1043;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_4_d1 = 21'd0;
        end else begin
            sum_V_4_d1 = 'bx;
        end
    end else begin
        sum_V_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_4_we1 = 1'b1;
    end else begin
        sum_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_5_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_5_address0 = i3_fu_459_p1;
        end else begin
            sum_V_5_address0 = 'bx;
        end
    end else begin
        sum_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_5_address1 = sum_V_5_addr_reg_947_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_5_address1 = sum_V_5_addr_1_reg_899_pp0_iter3_reg;
        end else begin
            sum_V_5_address1 = 'bx;
        end
    end else begin
        sum_V_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_5_ce0 = 1'b1;
    end else begin
        sum_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_5_ce1 = 1'b1;
    end else begin
        sum_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_5_d1 = ret_V_7_5_reg_1048;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_5_d1 = 21'd0;
        end else begin
            sum_V_5_d1 = 'bx;
        end
    end else begin
        sum_V_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_5_we1 = 1'b1;
    end else begin
        sum_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_6_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_6_address0 = i3_fu_459_p1;
        end else begin
            sum_V_6_address0 = 'bx;
        end
    end else begin
        sum_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_6_address1 = sum_V_6_addr_reg_953_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_6_address1 = sum_V_6_addr_1_reg_905_pp0_iter3_reg;
        end else begin
            sum_V_6_address1 = 'bx;
        end
    end else begin
        sum_V_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_6_ce0 = 1'b1;
    end else begin
        sum_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_6_ce1 = 1'b1;
    end else begin
        sum_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_6_d1 = ret_V_7_6_reg_1053;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_6_d1 = 21'd0;
        end else begin
            sum_V_6_d1 = 'bx;
        end
    end else begin
        sum_V_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_6_we1 = 1'b1;
    end else begin
        sum_V_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_976)) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_7_address0 = i2_fu_471_p1;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_7_address0 = i3_fu_459_p1;
        end else begin
            sum_V_7_address0 = 'bx;
        end
    end else begin
        sum_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_7_address1 = sum_V_7_addr_reg_959_pp0_iter3_reg;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_7_address1 = sum_V_7_addr_1_reg_911_pp0_iter3_reg;
        end else begin
            sum_V_7_address1 = 'bx;
        end
    end else begin
        sum_V_7_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_447_p2 == 1'd0) & (tmp_6_reg_851 == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        sum_V_7_ce0 = 1'b1;
    end else begin
        sum_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_7_ce1 = 1'b1;
    end else begin
        sum_V_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((tmp_6_reg_851 == 1'd1)) begin
            sum_V_7_d1 = ret_V_7_7_reg_1058;
        end else if (((tmp_8_reg_855 == 1'd1) & (tmp_6_reg_851 == 1'd0))) begin
            sum_V_7_d1 = 21'd0;
        end else begin
            sum_V_7_d1 = 'bx;
        end
    end else begin
        sum_V_7_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_6_reg_851 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_8_reg_855 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_6_reg_851 == 1'd0)))) begin
        sum_V_7_we1 = 1'b1;
    end else begin
        sum_V_7_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_s_fu_447_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_s_fu_447_p2 == 1'd1)) | ((ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign StreamIn_V_Data_V0_status = (StreamIn_V_User_V_empty_n & StreamIn_V_Data_V_empty_n);

assign StreamIn_V_Data_V_read = StreamIn_V_Data_V0_update;

assign StreamIn_V_User_V_read = StreamIn_V_Data_V0_update;

assign StreamOut_V_Data_V1_status = (StreamOut_V_User_V_full_n & StreamOut_V_Data_V_full_n);

assign StreamOut_V_Data_V_din = tmp_Data_V_fu_158;

assign StreamOut_V_Data_V_write = StreamOut_V_Data_V1_update;

assign StreamOut_V_User_V_din = tmp_User_V_reg_978_pp0_iter9_reg;

assign StreamOut_V_User_V_write = StreamOut_V_Data_V1_update;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b0 == StreamOut_V_Data_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0)) | ((1'b0 == StreamIn_V_Data_V0_status) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b0 == StreamOut_V_Data_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0)) | ((1'b0 == StreamIn_V_Data_V0_status) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b0 == StreamOut_V_Data_V1_status) & (ap_enable_reg_pp0_iter10 == 1'b1) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0)) | ((1'b0 == StreamIn_V_Data_V0_status) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter10 = ((1'b0 == StreamOut_V_Data_V1_status) & (tmp_s_reg_860_pp0_iter9_reg == 1'd0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (1'b0 == StreamIn_V_Data_V0_status);
end

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_976 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_s_fu_447_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_fu_495_p0 = grp_fu_495_p00;

assign grp_fu_495_p00 = reg_399;

assign grp_fu_495_p1 = 44'd3728271;

assign grp_fu_505_p0 = grp_fu_505_p00;

assign grp_fu_505_p00 = reg_403;

assign grp_fu_505_p1 = 44'd3728271;

assign grp_fu_515_p0 = grp_fu_515_p00;

assign grp_fu_515_p00 = reg_407;

assign grp_fu_515_p1 = 44'd3728271;

assign grp_fu_525_p0 = grp_fu_525_p00;

assign grp_fu_525_p00 = reg_411;

assign grp_fu_525_p1 = 44'd3728271;

assign grp_fu_535_p0 = grp_fu_535_p00;

assign grp_fu_535_p00 = reg_415;

assign grp_fu_535_p1 = 44'd3728271;

assign grp_fu_545_p0 = grp_fu_545_p00;

assign grp_fu_545_p00 = reg_419;

assign grp_fu_545_p1 = 44'd3728271;

assign grp_fu_555_p0 = grp_fu_555_p00;

assign grp_fu_555_p00 = reg_423;

assign grp_fu_555_p1 = 44'd3728271;

assign grp_fu_565_p0 = grp_fu_565_p00;

assign grp_fu_565_p00 = reg_427;

assign grp_fu_565_p1 = 44'd3728271;

assign i2_fu_471_p1 = i_reg_388;

assign i3_fu_459_p1 = i_reg_388;

assign i_2_fu_453_p2 = (i_reg_388 + 14'd1);

assign p_Result_12_7_fu_797_p9 = {{{{{{{{tmp_V_7_trunc_reg_1098}, {tmp_V_6_trunc_reg_1093}}, {tmp_V_5_trunc_reg_1088}}, {tmp_V_4_trunc_reg_1083}}, {tmp_V_3_trunc_reg_1078}}, {tmp_V_2_trunc_reg_1073}}, {tmp_V_1_trunc_reg_1068}}, {tmp_V_0_trunc_reg_1063}};

assign p_Result_1_fu_584_p4 = {{tmp_Data_V_5_reg_965[31:16]}};

assign p_Result_2_fu_603_p4 = {{tmp_Data_V_5_reg_965[47:32]}};

assign p_Result_3_fu_622_p4 = {{tmp_Data_V_5_reg_965[63:48]}};

assign p_Result_4_fu_641_p4 = {{tmp_Data_V_5_reg_965[79:64]}};

assign p_Result_5_fu_660_p4 = {{tmp_Data_V_5_reg_965[95:80]}};

assign p_Result_6_fu_679_p4 = {{tmp_Data_V_5_reg_965[111:96]}};

assign p_Result_7_fu_698_p4 = {{tmp_Data_V_5_reg_965[127:112]}};

assign ret_V_7_1_fu_597_p2 = (rhs_V_1_fu_593_p1 + reg_403);

assign ret_V_7_2_fu_616_p2 = (rhs_V_2_fu_612_p1 + reg_407);

assign ret_V_7_3_fu_635_p2 = (rhs_V_3_fu_631_p1 + reg_411);

assign ret_V_7_4_fu_654_p2 = (rhs_V_4_fu_650_p1 + reg_415);

assign ret_V_7_5_fu_673_p2 = (rhs_V_5_fu_669_p1 + reg_419);

assign ret_V_7_6_fu_692_p2 = (rhs_V_6_fu_688_p1 + reg_423);

assign ret_V_7_7_fu_711_p2 = (rhs_V_7_fu_707_p1 + reg_427);

assign ret_V_7_fu_578_p2 = (rhs_V_fu_574_p1 + reg_399);

assign rhs_V_1_fu_593_p1 = p_Result_1_fu_584_p4;

assign rhs_V_2_fu_612_p1 = p_Result_2_fu_603_p4;

assign rhs_V_3_fu_631_p1 = p_Result_3_fu_622_p4;

assign rhs_V_4_fu_650_p1 = p_Result_4_fu_641_p4;

assign rhs_V_5_fu_669_p1 = p_Result_5_fu_660_p4;

assign rhs_V_6_fu_688_p1 = p_Result_6_fu_679_p4;

assign rhs_V_7_fu_707_p1 = p_Result_7_fu_698_p4;

assign rhs_V_fu_574_p1 = tmp_9_fu_571_p1;

assign start_out = real_start;

assign storemerge_fu_827_p3 = ((tmp_8_reg_855[0:0] === 1'b1) ? 32'd0 : tmp_5_reg_1103);

assign tmp_5_fu_822_p2 = (cntr_load_reg_846 + 32'd1);

assign tmp_6_fu_435_p2 = ((cntr < 32'd9) ? 1'b1 : 1'b0);

assign tmp_8_fu_441_p2 = ((cntr == 32'd9) ? 1'b1 : 1'b0);

assign tmp_9_fu_571_p1 = tmp_Data_V_5_reg_965[15:0];

assign tmp_s_fu_447_p2 = ((i_reg_388 == 14'd10240) ? 1'b1 : 1'b0);

endmodule //pix_average
